query ($parent: String, $filter: NodeFilter, $perPage: Long, $page: Long) {
  node(uuid: $parent) {
    uuid
    nodes: children(filter: $filter, perPage: $perPage, page: $page) {
      totalCount
      pageCount
      elements {
        uuid
        schema {
          name
        }
        displayName
        isContainer
      }
    }
    breadcrumb {
      uuid
      text: displayName
    }
  }
}
