name: Node CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install, build, and test
      run: npm ci
    - name: build
      run: npm run build
    - name: run mesh
      run: npm run mesh-daemon
    - name: e2e tests
      run: npm run e2e-ci
