name: Build & Test

on: push

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: npm ci
    - name: build
      run: npm run build
    - name: run mesh
      run: npm run mesh-daemon
    - name: e2e tests
      run: npm run e2e-ci
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: npm ci
    - name: build
      run: npm run test-ci
